name: radiodigital
description: Rádio Digital - Estações e Reprodutor
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  just_audio: ^0.9.36
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: Newsreader
      fonts:
        - asset: lib/assets/fonts/Newsreader/Newsreader-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Newsreader/Newsreader-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Newsreader/Newsreader-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Newsreader/Newsreader-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Newsreader/Newsreader-Italic.ttf
          style: italic
    - family: Manrope
      fonts:
        - asset: lib/assets/fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700